{% set name = "ensureconda" %}
{% set version = "1.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ee70b75f6aa67fca5b72bec514e66deb016792959763cbd48720cfe051a24a4

build:
  number: 0
  noarch: python
  entry_points:
    - ensureconda = ensureconda.cli:ensureconda_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - hatchling >=0.21.1
    - hatch-vcs
  run:
    - appdirs
    - click >=5.1
    - filelock
    - python >=3.7
    - requests >=2

test:
  imports:
    - ensureconda
  commands:
    - pip check
    - ensureconda --help
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/ensureconda
  summary: Install and run applications packaged with conda in isolated environments
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - mariusvniekerk
