{% set name = "ensureconda" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/86/93/158dc5122fe7f433b7e0cd4a9ac28f416212a478ace36f26460de7b5fd1d/ensureconda-{{ version }}.tar.gz
  sha256: a71487b31d2676f1270ba14f76485b68a9a32493960b5d0f404d63b114ad7f2c

build:
  entry_points:
    - ensureconda = ensureconda.cli:ensureconda_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - click >=5.1
    - filelock
    - packaging
    - requests >=2

test:
  imports:
    - ensureconda
  commands:
    - pip check
    - ensureconda --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/conda-incubator/ensureconda
  summary: Lightweight bootstrapper for a conda executable
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - mariusvniekerk
    - maresb
